//go:build tinygo

// Code generated by "bleriot gen"; DO NOT EDIT.

package main

import (
	"github.com/burgrp/bleriot/lib/node"
	"github.com/burgrp/hw-fan-switch/fw/spec"
)

func main() {
	bleriotMain(node.Provisioning{
		Address:      [4]byte{0x08, 0xDE, 0x7C, 0x4A},
		Key:          [16]byte{0xF7, 0xBC, 0x67, 0x20, 0xB8, 0x4E, 0x5E, 0x73, 0xB6, 0x43, 0x55, 0xA3, 0xA4, 0x91, 0x57, 0xA5},
		Channel:      49,
		SpreadFactor: 0,
	}, spec.Config{DefaultDuty: 0x1e, LowDutyThreshold: 0x5, LowDutyKickstart: 0x1e})
}
